name = "TriangularShapedCloudInterpolation"
uuid = "51f55a63-7ec5-4b6d-a5a9-9bbf03ec1f62"
authors = ["LudwigBoess <lboess@usm.lmu.de>"]
version = "0.0.1"

[deps]
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
DocumenterTools = "35a29f4d-8980-5a13-9543-d66fff28ecb8"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[compat]
Documenter = "0.25"
julia = "1"
